- name: Check if server is reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping the server
      ansible.builtin.ping:
      register: ping_result
      ignore_errors: yes  # Prevent failure on unreachable hosts

    - name: Debug ping results
      ansible.builtin.debug:
        msg: "{{ ping_result }}"

    - name: Send alert if a server is unreachable
      ansible.builtin.uri:
        url: "https://discord.com/api/webhooks/1341011025926819861/iwbomQaEk5e6Y8MBRx47ln0hFPd-TPFBj3TjIwZBJfSSpfbSqAU0nM46Z023GgJamgQy"
        method: POST
        body_format: json
        body: >-
          {
            "username": "Server Monitor",
            "embeds": [
              {
                "title": "🚨 Server Down Alert 🚨",
                "description": "Server **{{ inventory_hostname }}** ({{ ansible_host }}) is **UNREACHABLE**! ❌",
                "color": 15158332
              }
            ]
          }
        status_code: 204
        validate_certs: no
      when: ping_result.unreachable is defined and ping_result.unreachable
