---
- name: Reboot a specific EC2 instance
  hosts: localhost
  gather_facts: no
  become: false
 
  vars:
    instance_ids:  
      - "i-xxxxxxxxxxxxxxxxx"
      - "i-yyyyyyyyyyyyyyyyy"
      - "i-zzzzzzzzzzzzzzzzz"
    aws_region: "us-east-1"
 
  tasks:
    - name: Validate provided instance ID
      fail:
        msg: "Invalid instance ID provided! Choose from: {{ instance_ids }}"
      when: instance_id not in instance_ids
 
    - name: Reboot the selected EC2 instance
      shell: aws ec2 reboot-instances --instance-ids {{ instance_id }} --region {{ aws_region }}
      async: 1
      poll: 0
      ignore_errors: yes
 
    - name: Show rebooted instance ID
      debug:
        msg: "Reboot command sent for instance: {{ instance_id }}"
