---
- name: Ping servers and send alerts if down
  hosts: localhost
  gather_facts: no

  vars:
    discord_webhook: "https://intelliconnectq.webhook.office.com/webhookb2/de3ea671-d7d1-4732-83fa-0fa42a8eee01@bd0edc69-11ea-4701-85eb-20002872112d/IncomingWebhook/d054f9d877484cdf986de333e734dd65/6bd0e637-7640-43ef-882a-4a24cdbad1fd/V277YTI6t9PUGsOKy7iseqk2sBSg4_p0_v4INDvOYrjY41"
    servers:
      - IP: "13.212.6.179"
        Name: "demo-server"
        Description: "server for running scripts"
        Cloud: "AWS"
        Region: "Oregon"

      - IP: "20.84.81.10"
        Name: "Database Server"
        Description: "unreachable server"
        Cloud: "Azure"
        Region: "Virginia"

  tasks:
    - name: Ping servers
      shell: "ping -c 4 {{ item.IP }}"
      register: ping_result
      ignore_errors: yes
      with_items: "{{ servers }}"

    - name: Print message based on ping reachability for each IP
      debug:
        msg: "Ping to {{ item.item.Name }} ({{ item.item.IP }}) {{ 'succeeded' if item.rc == 0 else 'failed' }}"
      with_items: "{{ ping_result.results }}"

    - name: Send alert on Discord for unreachable servers
      uri:
        url: "{{ discord_webhook }}"
        method: POST
        body_format: json
        body: >-
          {
            "username": "Server Monitor",
            "avatar_url": "https://cdn-icons-png.flaticon.com/512/2098/2098403.png",
            "embeds": [
              {
                "title": ":rotating_light: Server Down Alert!",
                "description": ":red_circle: **{{ item.item.Name }} ({{ item.item.IP }}) is NOT reachable!**",
                "color": 15158332,
                "fields": [
                  {
                    "name": "🌍 Cloud",
                    "value": "{{ item.item.Cloud }}",
                    "inline": true
                  },
                  {
                    "name": "📍 Region",
                    "value": "{{ item.item.Region }}",
                    "inline": true
                  },
                  {
                    "name": "📄 Description",
                    "value": "{{ item.item.Description }}",
                    "inline": false
                  },
                  {
                    "name": "🔗 Reference URL",
                    "value": "[Check Dashboard](https://your-dashboard-url)"
                  }
                ]
              }
            ]
          }
        status_code: 204
        validate_certs: no
      with_items: "{{ ping_result.results }}"
      when: item.rc is defined and item.rc != 0
