---
- name: Ping servers and send alerts if down
  hosts: all
  gather_facts: no
  tasks:
    - name: Ping the servers
      ping:
      register: ping_result
      ignore_unreachable: yes

    - name: Clear host errors to ensure alerts run for unreachable hosts
      meta: clear_host_errors

    - name: Send alert if a server is unreachable
      uri:
        url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
        method: POST
        headers:
          Content-Type: "application/json"
        body: >
          {
            "content": ":x: **Server Unreachable!**\n🔹 **Hostname:** `{{ inventory_hostname }}`\n🔹 **IP:** {{ ansible_host }}"
          }
        body_format: json
        status_code: [200]
      when: ping_result.unreachable is defined
